### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by jlkiri** [jbr/async-sqlx-session#17]
How can I disable logging when I use it with `tide` ? Currently it displays every query in my terminal as `sqlx::query SOME_QUERY`.

**Comment by ghost** [comment]
I think sqlx is using `env_logger` and unfortunately it is all info.

So I think we need to config it correctly, such as `RUST_LOG=your_cargo=debug` instead of just `RUST_LOG=debug`

**Comment by jbr** [comment]
closing this, as the interaction between sqlx's logging output and tide's default logger is out of the control of this crate
